### ISSUE TITLE
Consulta sobre la liberación de memoria dinámica en caso de error

### ISSUE THREAD

**Issue by gregoriotiscornia** [PI-ITBA/TPE_Dic_23#16]
Con nuestro grupo tenemos la duda si es necesario liberar la memoria dinamica reservada cuando el front-end decide finalizar el programa porque hubo algun error en el back (falta de memoria, dato invalido, etc).

**Comment by marcelogarberoglio** [comment]
En este caso el front  puede finalizar la ejecución sin liberar memoria

**Comment by gregoriotiscornia** [comment]
Perfecto, muchas gracias
