### ISSUE TITLE
Creacion de ejecutables

### ISSUE THREAD

**Issue by NaPrado** [PI-ITBA/TPE_Dic_23#21]
Buenos Dias, quisiera saber que es preferible, crear 2 ejecutables(uno para cada ciudad y que el usuario use el que prefiera) o aclarar en el reedMe los parametros a modificar del make file para generar cada uno de los ejecutables. Desde ya muchas gracias.

**Comment by fmeola** [comment]
Hola.
Crear dos ejecutables

**Comment by NaPrado** [comment]
Genial, gracias Franco
