### ISSUE TITLE
Query 4

### ISSUE THREAD

**Issue by NaPrado** [PI-ITBA/TPE_Dic_23#22]
Buenas, nos surgio una duda con la query 4:
Que deberia de pasar si no hay un viaje en alguna estacion? Se debe mostrar alguna informacion del tipo empty, es responsable el front de comprobar si en la estacion iterada existe algun viaje, o directamente desde el back se debe ignorar esa estacion y mostrar la siguiente?
El problema surge de pensar que quizas el front quisiera mostrar alguna informacion diferente para las estaciones no visitadas o mostrar que no tienen viajes o alguna funcion nueva que muestre otros datos para esta estaciones.
Por otro lado el back quiere sacar la responsabilidad del usuario de tener que verificar si alguna estacion esta vacia ya que al no tener que mostrarse esta podria acceder a null.

**Comment by fmeola** [comment]
Hola.
Es verdad, el enunciado no aclara como proceder respecto a una estación sin viajes iniciados en la Query 4 (En la Query 5 si se explicita el "Empty" para un mes)
Como no se indica entonces pueden tomar ustedes una decisión (ya sea no listar las estaciones sin viajes o listarlas con un Empty en la segunda y tercer columna). Tomaremos ambas salidas como válidas.

**Comment by NaPrado** [comment]
Gracias Franco
