### ISSUE TITLE
Query 4 - Dataset reducido

### ISSUE THREAD

**Issue by JoaquinPlaCardenasITBA** [PI-ITBA/TPE_Dic_23#23]
Corriendo un dataset reducido nos percatamos que nuestra implementacion de query 4 muestra estaciones populares incluso si no hay viajes a ellas

Ejemplo de output
![image](https://github.com/PI-ITBA/TPE_Dic_23/assets/153039379/efdb4419-6cbc-4301-9f8a-2abacba9c208)
Como se puede observar en la imagen hay varias estaciones que tienen un lugar popular pero con 0 viajes.

No sabemos si entra en el scope del TP o no lidiar con esta situacion, pero queriamos saber si vale la pena no guardar esta informacion para el usuario cuando se ordena la lista.

**Comment by fmeola** [comment]
Hola.
Se contestó hoy acá: https://github.com/PI-ITBA/TPE_Dic_23/issues/22

**Comment by JoaquinPlaCardenasITBA** [comment]
Oh, no lo vi.
Gracias!
