### ISSUE TITLE
Hang al hacer fclose

### ISSUE THREAD

**Issue by JoaquinPlaCardenasITBA** [PI-ITBA/TPE_Dic_23#24]
Probando el programa me ha pasado varias veces que al hacer flcose u closeHTMLTable (en el fclose), el mismo se quede estancado. Si pauso la ejecucion con el debuger se lo puede ver dando vueltas por el dissasembly (adjunto una imagen con stack trace mas profundo que pude ver)

![image](https://github.com/PI-ITBA/TPE_Dic_23/assets/153039379/6e414d31-517f-407b-afec-02e422b74acb)

No pudimos encontrar la causa del problema. Como podemos proceder?

**Comment by marcelogarberoglio** [comment]
Es raro, pero como ya se habrán dado cuenta, FILE es un TAD, donde fopen es equivalente a las funciones "new" y fclose se usa -entre otras cosas- para liberar la memoria reservada por fopen. Puede ser que en algún momento hayan pisado memoria dinámica y por eso falle. ¿Lo están probando en pampero o en una PC con Windows?
Traten de probar -por ejemplo- comentando la sección donde generan la query, para que sólo abra los archivos, complete con los títulos y luego los cierre. Si nunca falla es porque seguramente al generar la query están pisando memoria.

**Comment by JoaquinPlaCardenasITBA** [comment]
Ahi acabo de comentar el codigo que escribe las queries, al tercer intento volvio a pasar.

**Comment by JoaquinPlaCardenasITBA** [comment]
Comentando tambien la impresion de headers en pareceria funcionar (dificil decir ya que el preoblema es intermitente)

**Comment by JoaquinPlaCardenasITBA** [comment]
Al tener algun fprintf el error aparece, aca pongo los que tenemos a ver si pueden ver algo que sobresalga

`fprintf(queriesCSV[0], "bikeStation;memberTrips;casualTrips;allTrips\n");`
`fprintf(queriesCSV[1], "bikeStation;bikeEndStation;oldestDateTime\n");`
`fprintf(queriesCSV[2], "weekDay;startedTrips;endedTrips\n");`
`fprintf(queriesCSV[3], "bikeStation;mostPopRouteEndStation;mostPopRouteTrips\n");`
`fprintf(queriesCSV[4], "month;loopsTop1St;loopsTop2St;loopsTop3St\n");`

`fprintf(queriesCSV[i - 1], "%s", line)`

Con FILE * queriesCSV[QUERIES];
Con QUERIES definido como 5
Con line siendo un char[1024] al que se le hace un sprintf con el formato y los datos

**Comment by marcelogarberoglio** [comment]
No contestamos sobre implementación. Entre uds deben  ver cómo hacer que el código quede modularizado y lo más claro posible, no sólo para evitar errores sino que sea más fácil corregirlos.

**Comment by JoaquinPlaCardenasITBA** [comment]
El problema parece mas prominente en PC

**Comment by JoaquinPlaCardenasITBA** [comment]
Y con eso se encontro al culpable: Mi antivirus
Parece que cada tanto decide no dejar al programa escribir y lo trata de archivo sospechoso por alguna razon.
