### ISSUE TITLE
Algoritmos de ordenamiento (autoría)

### ISSUE THREAD

**Issue by tomaspietravallo** [PI-ITBA/TPE_Dic_23#3]
Hola buenas!

Quería saber cómo deberíamos hacer si quisiéramos utilizar algún algoritmo de ordenamiento que no fuera parte de la biblioteca standard (como `qsort`).

En este caso particular dados los datos con los que estamos trabajando creo que quizás [Radix Sort](https://en.wikipedia.org/wiki/Radix_sort) podría ser más eficiente (se podría testear y comparar)... pero dado que radix sort no es de nuestra autoría, cómo deberíamos manejarnos?

Teníamos pensando leer varias referencias y en base a eso implementarlo nosotros (en lugar de copiar y pegar de ningún lado). Y podríamos poner un comentario por encima de la función citando las referencias. Se puede hacer eso? O se espera que no hagamos algo de este estilo y si necesitamos ordenar algo utilicemos cosas cómo `qsort`?

Gracias!

**Comment by marcelogarberoglio** [comment]
Radix sort, efectivamente, es más eficiente si las claves son enteros, ya que no necesita realizar comparaciones.
Pero teniendo en cuenta los alcances de la materia, pueden usar qsort.
Otros algoritmos de ordenación, que se adecúen mejor a distintos tipos de datos, los verán en EDA

**Comment by tomaspietravallo** [comment]
Hola @marcelogarberoglio , reabro este issue por las cuestiones de Autoria. 

Quiero implementar un algoritmo/estructura de datos para la cual me estoy basando de manera importante en el libro "Programing Abstractions in C" encontrado en la biblioteca del ITBA. Seria necesario aclarar esto en el repositorio? Un simple comentario sobre la declaración de mi estructura seria suficiente?

Muchas gracias,
Saludos

**Comment by marcelogarberoglio** [comment]
Muy buen libro. Con un simple comentario es suficiente ("Basado en..."), no hace falta una documentación detallada
Por nada
Saludos
