### ISSUE TITLE
Makefile -j[XXX] - tiempo de compilado

### ISSUE THREAD

**Issue by tomaspietravallo** [PI-ITBA/TPE_Dic_23#5]
Hola buenas

Tengo entendido que dentro del README.md deberíamos incluir una pequeña explicación de como compilar nuestro programa. Queria saber si se podia utilizar la opcion `-j` de GNU Make, dado que make resulta ser mucho mas lento que gcc sin utlizar esta opcion

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `gcc -Wall -pedantic -std=c99 -Werror -fsanitize=address main.c ./src/BikeStation.c ./src/CityStations.c -Iheaders -o Binary.out` | 68.2 ± 1.0 | 66.2 | 70.1 | 1.00 |
| `make all` | 116.4 ± 13.3 | 106.9 | 162.8 | 1.71 ± 0.20 |

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `gcc -Wall -pedantic -std=c99 -Werror -fsanitize=address main.c ./src/BikeStation.c ./src/CityStations.c -Iheaders -o Binary.out` | 68.7 ± 2.0 | 66.6 | 75.1 | 1.04 ± 0.04 |
| `make all -j 20` | 65.8 ± 1.6 | 63.6 | 72.2 | 1.00 |

Aca dejo unas tablas de ejemplo mostrando que gcc es mucho mas rápido, lo que yo intuyo es que GCC ya procesa los archivos en paralelo, mientras que make no lo hace salvo que sea pedido explícitamente con `-j [num]`. Se podría incluir el flag como parte del comando explicando como compilar? O no deberíamos preocuparnos por el tiempo de compilación?

Nota: El archivo Makefile esta configurado para que primero cree todos los .o relevantes y luego los linkedite con main.o, si quieren puedo incluir aca el archivo que tenemos

**Comment by fmeola** [comment]
Hola Tomás.
No se preocupen por el tiempo de compilación. 
Desde ya podés usar el flag y en la entrega podés dejar un valor por defecto que funcione en el entorno de Pampero (que es donde vamos a compilar los TPEs y hacer las pruebas) junto un comentario en el README por si lo queremos cambiar.
