### ISSUE TITLE
.csv de estaciones

### ISSUE THREAD

**Issue by lmoliveto** [PI-ITBA/TPE_Dic_23#7]
Buen día! Una consulta sobre el archivo de estaciones que recibimos como argumento. Puede haber id's repetidos?

**Comment by marcelogarberoglio** [comment]
En los csv no debería haber id's repetidos.
Si bien acá les pedimos front y back deberían pensar ambos en forma independiente.
Al momento de programar el backend tienen que pensar que un tercero (no uds) puede hacer otro front-end.
